version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 14
      - yum install -y gcc-c++ make 
      - curl -sL https://rpm.nodesource.com/setup_14.x | -E bash - 
      - yum install -y nodejs 
  pre_build:
    commands:
    - echo Installing dependencies
    - npm install
  build:
    commands:
      - echo Building
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: client



    